version: "3.8"

services:
  lana-discount-web:
    build: .
    container_name: lana-discount-web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=www.lana.discount,lana.discount
      - LETSENCRYPT_HOST=www.lana.discount,lana.discount
      - LETSENCRYPT_EMAIL=josh@lanaworld.app
    networks:
      - webproxy

networks:
  webproxy:
    external: true
